### ISSUE TITLE
"Error: Password contains an illegal unescaped character"

### ISSUE THREAD

**Issue by guillempuche** [Azure/azure-cosmos-db-emulator-docker#12]
My code is (I've changed localhost port to 8000 & mongodb port to 10000 with ```CosmosDB.Emulator.exe```):
```
var url = "mongodb://localhost:C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==@localhost:10000/admin?ssl=true"

MongoClient.connect(url, function(err, db) { 
    if (err) throw err; // Return error but run the program: $ return console.error(err);
   ...
};
```
And it produces this error:

```
Error: Password contains an illegal unescaped character
    at parseConnectionString (F:\Chatbots\Code\test\botframework-demo\node_modules\mongodb\lib\url_parser.js:287:13)
    at parseHandler (F:\Chatbots\Code\test\botframework-demo\node_modules\mongodb\lib\url_parser.js:119:14)
    at module.exports (F:\Chatbots\Code\test\botframework-demo\node_modules\mongodb\lib\url_parser.js:25:12)
    at connect (F:\Chatbots\Code\test\botframework-demo\node_modules\mongodb\lib\mongo_client.js:869:3)
    at connectOp (F:\Chatbots\Code\test\botframework-demo\node_modules\mongodb\lib\mongo_client.js:269:3)
    at executeOperation (F:\Chatbots\Code\test\botframework-demo\node_modules\mongodb\lib\utils.js:409:22)
    at MongoClient.connect (F:\Chatbots\Code\test\botframework-demo\node_modules\mongodb\lib\mongo_client.js:260:10)
    at Function.MongoClient.connect (F:\Chatbots\Code\test\botframework-demo\node_modules\mongodb\lib\mongo_client.js:481:22)
    at Object.<anonymous> (F:\Chatbots\Code\test\botframework-demo\test.js:145:13)
    at Module._compile (module.js:635:30)
```

I've also tried to change ```url``` for ```encodeURIComponent(url)```, but it produces the next error:
> Error: Invalid schema, expected `mongodb` or `mongodb+srv`

What I need to do?

**Comment by guillempuche** [comment]
_*My code is on **Node.js**_

I've found the solution:
```
// 'key' is defined before, if not encodeURIComponent() returns 'undefined'
const key = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="; 
const url = `mongodb://localhost:${encodeURIComponent(key)}@localhost:10250/admin?ssl=true`

// Connect to the database or 'db'
// Encode the key only with encodeURIComponent() is who only encode '/', not encodeURI() or escape()
// http://www.javascripter.net/faq/escape.htm
MongoClient.connect(url, function(err, db) { //encodeURIComponent(url)
    if (err) throw err;
    var dbo = db.db("test");
    console.log("MongoDB conectado")
   
});
```

These are the conclusions:
1. I need to declare the 'key' before the url is declared
2. I need to encodeURIComponent() for '/' and all other special characters from the key, not encodeURI() or escape()
