### ISSUE TITLE
Spring Data query fails with innerErrorMessage "Index does not have options 16" #cosmosEmulatorVnextPreview

### ISSUE THREAD

**Issue by kmandalas** [Azure/azure-cosmos-db-emulator-docker#128]
Using Java 17 and Spring 3.2.2 with `spring-cloud-azure-starter-data-cosmos`, queries like `findAllByPrincipalAndTimestampGreaterThanEqualOrderByTimestampAsc` fail with error message:
`
com.azure.cosmos.CosmosException: {"innerErrorMessage":"Index does not have options 16, StatusCode: InternalServerError"...}`

The Spring Data Repository is the following:

```
@Repository
public interface TicketAuditRepository extends CosmosRepository<CustomAudit, String> {

    List<CustomAudit> findAllByPrincipalAndTimestampGreaterThanEqualOrderByTimestampAsc(String principal, Instant instant);

}
```

The CosmosDB Container Document is defined like:

```
@Builder
@Data
@Container(containerName = "audits")
public class CustomAudit {

    @Id
    @GeneratedValue
    private String id;

    private final Instant timestamp;

    @PartitionKey
    private final String principal;

    private final String type;

    private final Map<String, Object> data;

}

```

**Comment by TheovanKraay** [comment]
@kmandalas this should work, I am unable reproduce your error. However, a couple of things worth pointing out with this version of the emulator which are mentioned in the [documentation](https://learn.microsoft.com/azure/cosmos-db/emulator-linux). 

First, only `gateway` mode is supported. In Spring Data Cosmos, `direct` mode is used by default, so in app configuration, you need to have something like:

```java
    @Bean
    public CosmosClientBuilder cosmosClientBuilder() {
        DirectConnectionConfig directConnectionConfig = DirectConnectionConfig.getDefaultConfig();
        directConnectionConfig.setMaxRequestsPerConnection(10);
        return new CosmosClientBuilder()
            .endpoint(properties.getUri())
            .key(properties.getKey()) 
            .gatewayMode();
    }
```

Also, emulator runs by default in `http' mode. Currently the Java SDK does not yet support http (it will very soon). For now, you would need to start the container with https:

```shell
sudo docker run --detach --publish 8081:8081 --publish 1234:1234 mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview --protocol https
```

Finally, for https you would need to install new certs for https (again, we are removing this restriction soon, but for now these steps are needed). Once emulator is started, follow instructions [here](https://learn.microsoft.com/azure/cosmos-db/emulator-linux#installing-certificates-for-java-sdk) to install cert.

If you have done all this already and still have problems, or it does not work after taking these steps, please share the full project code if possible.

**Comment by kmandalas** [comment]
@TheovanKraay I did have `gateway` mode enabled and HTTPS with the certificated imported in my JDK. It was a first attempt to run my integration tests suite against the new emulator. I can confirm that the problem I initially reported cannot be reproduced when I tried it standalone at a new project. The root cause must be something else that I need to investigate further and isolate it. Therefore this issue can be closed. 

However 80% of the tests previously working fine on Windows and Linux machines, now fail when running on macOS (Apple Silicon) against the new emulator, for reasons already reported as I see in the meantime.

**Comment by xgerman** [comment]
@kmandalas  thank you for adding the details we will look into the query and get back to you.

**Comment by kmandalas** [comment]
Any updates on this? The "IN" clause is not supported?

**Comment by TheovanKraay** [comment]
@kmandalas apologies for the slow update - I am not able to reproduce your exact error, but am not running this from testcontainers due to some issues with that. Will look at this again and update on progress by the end of the week.

**Comment by kmandalas** [comment]
Thank you, just to add for your consideration that it works if I run a query like this:
```

@Query("SELECT * FROM c WHERE c.principal = @principal AND c.type IN ('USER_ACTION_X', 'USER_ACTION_Y')")
 List<DemoAudit> findAllByPrincipalAndTypes(@Param("principal") String principal);
```

but it does not work this way:

`List<DemoAudit> findAllByPrincipalAndTypeIn(String principal, List<String> types);`

**Comment by kmandalas** [comment]
I re-tried today after pulling latest image. The error remains, like:

```
2025-02-03T10:54:33.206+02:00 DEBUG 18512 --- [           main] c.a.c.implementation.SqlQuerySpecLogger  : SELECT * FROM ROOT r WHERE (r.principal = @principal0 AND r.type IN (@p1,@p2)) 
2025-02-03T10:54:33.213+02:00 ERROR 18512 --- [ctor-http-nio-1] c.a.c.i.query.DocumentProducer           : Unexpected failure, Context: n/a

com.azure.cosmos.CosmosException: {"innerErrorMessage":"Index does not have options 16 Cosmos query text: SELECT * FROM ROOT r WHERE (r.principal = @principal0 AND r.type IN (@p1,@p2))  -> SELECT * FROM %s AS r WHERE (cosmos_catalog.cosmos_eq(r.document, $1 ) AND cosmos_catalog.cosmos_in(r.document, $2 )), StatusCode: InternalServerError","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.54.0 MacOSX/14.6.1 JRE/21.0.2 az-sd-cos/5.9.1az-sp-cos/5.9.1","activityId":"c85b0a7b-6383-468a-baca-cae30b336e2c","requestLatencyInMs":4,"requestStartTimeUTC":"2025-02-03T08:54:33.209114Z","requestEndTimeUTC":"2025-02-03T08:54:33.213444Z","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":["primary"],"retryContext":{"statusAndSubStatusCodes":null,"retryLatency":0,"retryCount":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatisticsList":[{"sessionToken":"0:-1#1","operationType":"Query","resourceType":"Document","statusCode":500,"subStatusCode":0,"requestCharge":0.0,"requestTimeline":[{"eventName":"connectionAcquired","startTimeUTC":"2025-02-03T08:54:33.209536Z","durationInMilliSecs":0.111},{"eventName":"connectionConfigured","startTimeUTC":"2025-02-03T08:54:33.209647Z","durationInMilliSecs":0.016},{"eventName":"requestSent","startTimeUTC":"2025-02-03T08:54:33.209663Z","durationInMilliSecs":0.258},{"eventName":"transitTime","startTimeUTC":"2025-02-03T08:54:33.209921Z","durationInMilliSecs":3.267},{"eventName":"received","startTimeUTC":"2025-02-03T08:54:33.213188Z","durationInMilliSecs":0.12}],"partitionKeyRangeId":null,"responsePayloadSizeInBytes":0,"exceptionMessage":"Index does not have options 16 Cosmos query text: SELECT * FROM ROOT r WHERE (r.principal = @principal0 AND r.type IN (@p1,@p2))  -> SELECT * FROM %s AS r WHERE (cosmos_catalog.cosmos_eq(r.document, $1 ) AND cosmos_catalog.cosmos_in(r.document, $2 )), StatusCode: InternalServerError","exceptionResponseHeaders":"{Transfer-Encoding=chunked, Server=PGSQL, x-ms-session-token=0:-1#1, x-ms-documentdb-partitionkeyrangeid=0, x-ms-interopandsdk-time-ms=2, x-ms-gatewayversion=2.0.0-unknown, Date=Mon, 03 Feb 2025 08:54:33 GMT, x-ms-activity-id=c85b0a7b-6383-468a-baca-cae30b336e2c, Content-Type=application/json}"}],"samplingRateSnapshot":1.0,"systemInformation":{"usedMemory":"51228 KB","availableMemory":"9385956 KB","systemCpuLoad":"(2025-02-03T08:54:33.065791Z 12.3%)","availableProcessors":11},"clientCfgs":{"id":1,"machineId":"uuid:6a42097a-eeea-4a0d-9a7a-81704a0fd266","connectionMode":"GATEWAY","numberOfClients":3,"excrgns":"[]","clientEndpoints":{"https://localhost:58710":3},"connCfg":{"rntbd":null,"gw":"(cps:1000, nrto:PT1M, icto:PT1M, p:false)","other":"(ed: false, cs: false, rv: true)"},"consistencyCfg":"(consistency: null, mm: true, prgns: [])","proactiveInitCfg":"","e2ePolicyCfg":"","sessionRetryCfg":""}}}
	at com.azure.cosmos.BridgeInternal.createCosmosException(BridgeInternal.java:478) ~[azure-cosmos-4.54.0.jar:4.54.0]
	at com.azure.cosmos.implementation.RxGatewayStoreModel.validateOrThrow(RxGatewayStoreModel.java:504) ~[azure-cosmos-4.54.0.jar:4.54.0]
	at com.azure.cosmos.implementation.RxGatewayStoreModel.lambda$toDocumentServiceResponse$1(RxGatewayStoreModel.java:365) ~[azure-cosmos-4.54.0.jar:4.54.0]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:194) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415) ~[reactor-netty-core-1.1.15.jar:1.1.15]
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:446) ~[reactor-netty-core-1.1.15.jar:1.1.15]
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:500) ~[reactor-netty-core-1.1.15.jar:1.1.15]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:782) ~[reactor-netty-http-1.1.15.jar:1.1.15]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114) ~[reactor-netty-core-1.1.15.jar:1.1.15]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475) ~[netty-handler-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1349) ~[netty-handler-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1389) ~[netty-handler-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]


org.springframework.core.convert.ConversionFailedException: Failed to convert from type [org.springframework.data.util.Streamable<?>] to type [java.util.List<com.example.demo.audits.DemoAudit>] for value [org.springframework.data.util.Streamable$$Lambda/0x000000d0015204a0@2f154d9b]
```

**Comment by zoltan-toth-mw** [comment]
It has nothing to do with spring. 
This also fails: 
```kotlin
cosmosContainer.readMany(ids.map { CosmosItemIdentity(PartitionKey(it), it) }, CosmosDbItem::class.java)
```

With `{"innerErrorMessage":"Index does not have options 16 Cosmos query text: SELECT * FROM c WHERE c.id IN ( @param0, @param1, @param2, @param3, @param4 ) -> SELECT * FROM %s AS c WHERE cosmos_catalog.cosmos_in(c.document, $1 ), StatusCode: InternalServerError"`

I ran`mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview` with testcontainer.

**Comment by kmandalas** [comment]
@xgerman has the effort been paused on resolving such issues?

**Comment by xgerman** [comment]
@kmandalas we have been working with our query team to address the issues but progress has been unfortunately slow.

**Comment by Ritvik-Jayaswal** [comment]
@AdamDotNet @kmandalas With the emulator version the included the new query engine, this issue should be fixed. You can try it with the latest version and the queries listed here should work without issue. (See https://github.com/Azure/azure-cosmos-db-emulator-docker/releases/tag/EN20260130)

**Comment by AdamDotNet** [comment]
@Ritvik-Jayaswal I can confirm that docker images published since November 18, 2025 started working adequately for my uses.

**Comment by kmandalas** [comment]
@Ritvik-Jayaswal confirmed working with latest version for my uses too.
