### ISSUE TITLE
Unable to Connect To Explorer - ERR_EMPTY_RESPONSE in Browser

### ISSUE THREAD

**Issue by awebre** [Azure/azure-cosmos-db-emulator-docker#135]
**Describe the bug**
When attempting to connect to the explorer by navigating to http://localhost:1234 after creating a fresh container, the browser reports "ERR_EMPTY_RESPONSE". The db itself is available and responding on http://localhost:8081. 

**To Reproduce**
1. Create a fresh container instance using the instructions listed [here](https://devblogs.microsoft.com/cosmosdb/introducing-the-new-linux-based-azure-cosmos-db-emulator-preview/)
2. Navigate to http://localhost:1234 in the browser
3. No response from the server and the browser reports ERR_EMPTY_RESPONSE

**Expected behavior**
According to documentation, this should be sufficient to see the Data Explorer.

**Screenshots**
Error in the browser on localhost:1234
![Image](https://github.com/user-attachments/assets/c2deecb0-d497-4a45-8abb-b3a32caa7c9d)
Browser is able to connect to localhost:8081 and return data:
![Image](https://github.com/user-attachments/assets/8bfd3149-62a1-4420-9ca0-75c3043b2f0f)

**Desktop (please complete the following information):**
 - OS: macOS 15.1.1 (M3 Max)
 - Browser: Edge
 - Version: vnext-preview
 - SDK version: n/a
 - SDK language: n/a

**Additional context**
Other things I have tried with no success:
- Changing the port mapping such that the host port is different to avoid any conflicts
- Using SSL with self-signed certificates (this resulted in the same scenario but over HTTPS)
- Leaving the emulator up over long periods of time to see if webpack was just slow (did not resolve itself, even overnight)
- Running as part of docker-compose, rather than running a one-off container (this is where I first noticed the issue)

**Comment by xgerman** [comment]
We are investigating docker compose related errors as part of https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/125 but I will keep that open so we can triage it further

**Comment by awebre** [comment]
@xgerman Thanks for the quick response!

I did run across that issue in doing some self-investigation, which is when I decided to strip everything down and _just_ run the container directly with `docker run` as mentioned in the docs. Unfortunately, I had the same result (ERR_EMPTY_RESPONSE when navigating to http://localhost:1234), so I don't believe this particular issue is docker-compose specific, though it's possible that I missed something or that this is ultimately still related to some networking issues.

If it helps, I can see some webpack-related messages in the logs on startup:
```
2024-11-27 17:00:37 <i> [webpack-dev-server] [HPM] Proxy created: /api  -> https://main.documentdb.ext.azure.com
2024-11-27 17:00:37 <i> [webpack-dev-server] [HPM] Proxy created: /proxy  -> https://main.documentdb.ext.azure.com
2024-11-27 17:00:37 <i> [webpack-dev-server] [HPM] Proxy rewrite rule created: "^/proxy" ~> ""
2024-11-27 17:00:37 <i> [webpack-dev-server] [HPM] Proxy created: /_explorer  -> https://localhost:8081
2024-11-27 17:00:37 <i> [webpack-dev-server] [HPM] Proxy created: /explorerProxy  -> https://localhost:8081
2024-11-27 17:00:37 <i> [webpack-dev-server] [HPM] Proxy rewrite rule created: "^/explorerProxy" ~> ""
2024-11-27 17:00:37 <i> [webpack-dev-server] [HPM] Proxy created: /72f988bf-86f1-41af-91ab-2d7cd011db47  -> https://login.microsoftonline.com/
2024-11-27 17:00:37 <i> [webpack-dev-server] Project is running at:
2024-11-27 17:00:37 <i> [webpack-dev-server] Loopback: https://localhost:1234/
2024-11-27 17:00:37 <i> [webpack-dev-server] Content not from webpack is served from '/root/cosmos-explorer/public' directory
```
 But when requests are made to `localhost:1234`, I don't see any corresponding logs.

**Comment by xgerman** [comment]
I just tried with the latest container by running `docker run --detach --publish 8081:8081 --publish 1234:1234  -e EXPLORER_PROTOCOL=https mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview` and going with Safari to https://localhost:1234 --

**Comment by xgerman** [comment]
@awebre  We pushed a new version so please give it another try.

**Comment by awebre** [comment]
I also gave this another try with the new image and saw the same behavior. Let me know if there's more that I can provide to help debug this

**Comment by xgerman** [comment]
Sorry to hear that. We are improving the data explorer and should have a new version soon. @christopheranderson  anything else he should try?

**Comment by bbrewer97202** [comment]
Having the same issue as awebre using vanilla commands straight from the docs. Empty reply happens with both 'docker run' and docker compose. Whenever http://localhost:1234 requested this appears in the logs:

_<i> [webpack-dev-middleware] wait until bundle finished: /_

I thought maybe the browser timeout was too short, but a curl with 10 minutes still returns empty response: 
curl --max-time 600 'http://localhost:1234'.

Apple M1 Pro, 16gb RAM, OS 14.7.1 with Docker version 27.2.1-rd (Rancher Desktop).

**Comment by xgerman** [comment]
Most of the team will be on break the next two weeks but we will release another version towards the end of this week + we will investigate this in the new year.

**Comment by christopheranderson** [comment]
Given that there aren't any errors from the dev-server, it's probably something in how the docker loopback to the host's localhost is interacting. It can be hard to know for certain without a reproduction. 

One thing I can try is explicitly binding to 0.0.0.0:1234, instead of just the default localhost. That'd match the behavior of the gateway being served from 8081. Other than that, I can come up with some documentation on what environment information would be helpful to debug.

**Comment by hectortosa** [comment]
I'm having the same error. I've tried using `--protocol https`, and this is the result:

```
⚡️ docker run -p 8081:8081 -p 1234:1234 mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview --protocol https --enable-explorer true --explorer-protocol 1234 --log-level trace
Release Version: 5e7ad955d634f2a882c4be3f4f5c17b51f029c68
Generating certificate
...................................................+++++
...............+++++
Generating a RSA private key
..................+++++
..............................................+++++
writing new private key to '/scripts/certs/rootCA.key'
-----
Signature ok
subject=C = US, ST = WA, O = SqlPostgresHostConsole, CN = localhost
Getting CA Private Key
/root/cosmos-explorer ~
~
DocDBTrace Information: 0 : SetupConfigurations {"GatewayListenAddress":"0.0.0.0","PostgresHostName":"127.0.0.1","PostgresPort":9712,"PostgresDatabase":"postgres","GatewayPublicEndpoint":"127.0.0.1","UserName":"cosmosdev","ApplicationInsightsConnectionString":"InstrumentationKey=ff1dbd63-a66b-43cd-9863-812458fa4ba6","ApplicationInsightsMeterName":"CosmosPGMetrics"}
DocDBTrace Information: 0 : Using certificate from /scripts/certs/domain.pfx
DocDBTrace Information: 0 : Npgsql Non-Transaction settings -c idle_in_transaction_session_timeout=60000 -c statement_timeout=60000
DocDBTrace Information: 0 : Starting up Kestrel runtime
Hosting environment: Production
Content root path: /publish/
Now listening on: https://0.0.0.0:8081
<i> [webpack-dev-server] [HPM] Proxy created: /api  -> https://cdb-ms-mpac-pbe.cosmos.azure.com
<i> [webpack-dev-server] [HPM] Proxy created: /proxy  -> https://cdb-ms-mpac-pbe.cosmos.azure.com
<i> [webpack-dev-server] [HPM] Proxy rewrite rule created: "^/proxy" ~> ""
<i> [webpack-dev-server] [HPM] Proxy created: /_explorer  -> https://localhost:8081
<i> [webpack-dev-server] [HPM] Proxy created: /explorerProxy  -> https://localhost:8081
<i> [webpack-dev-server] [HPM] Proxy rewrite rule created: "^/explorerProxy" ~> ""
<i> [webpack-dev-server] [HPM] Proxy created: /72f988bf-86f1-41af-91ab-2d7cd011db47  -> https://login.microsoftonline.com/
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: https://localhost:1234/
<i> [webpack-dev-server] Content not from webpack is served from '/root/cosmos-explorer/public' directory
  oid  | extname  | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition
-------+----------+----------+--------------+----------------+------------+-----------+--------------
 18892 | pgcosmos |       10 |         2200 | f              | 1.0        |           |
(1 row)

 initialize_cluster
--------------------

(1 row)
```

And I don't see any traces in the console when trying to access the explorer.

And when calling the endpoint:

```
⚡️ curl --max-time 600 'https://localhost:1234'


curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:1234
```

```
⚡️ curl --max-time 600 'http://localhost:1234'


curl: (52) Empty reply from server
```

From the browser:

![Image](https://github.com/user-attachments/assets/baab165b-66cc-41c8-a262-49e51bc6393f)

I have a MacBook M2 Pro with macOS Sequoia 15.2, and I'm using docker + colima.


I hope this help in some way :)

**Comment by diegowrhasta** [comment]
Bumping this up.

Trying to follow:

https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-develop-emulator?tabs=docker-linux%2Ccsharp&pivots=api-nosql

and

https://learn.microsoft.com/en-us/azure/cosmos-db/emulator-linux#installing-certificates-for-java-sdk

With .NET Core does not work when it comes to actually connecting to the container if we want to use a certificate. The explorer is fine in my case, but when trying to connect with the `CosmosClient` class it does not accept the self-signed certificate, only doing the workaround that completely skips over the SSL validation makes it "work" but when trying to do anything, it also fails under an exception, this is what I get when simply trying to create a Database:

```
at Microsoft.Azure.Documents.ConsistencyReader.GetMaxReplicaSetSize(DocumentServiceRequest entity)
   at Microsoft.Azure.Documents.ConsistencyReader.ReadAsync(DocumentServiceRequest entity, TimeoutHelper timeout, Boolean isInRetry, Boolean forceRefresh, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.ReplicatedResourceClient.InvokeAsync(DocumentServiceRequest request, TimeoutHelper timeout, Boolean isInRetry, Boolean forceRefresh, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass32_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, IRetryPolicy retryPolicy)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.RouterHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.RequestHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.AbstractRetryHandler.ExecuteHttpRequestAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`3 callShouldRetryException, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.AbstractRetryHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.RequestHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TelemetryHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.RequestHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.RequestHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.BaseSendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.SendAsync(String resourceUriString, ResourceType resourceType, OperationType operationType, RequestOptions requestOptions, ContainerInternal cosmosContainerCore, FeedRange feedRange, Stream streamPayload, Action`1 requestEnricher, ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.CosmosClient.<>c__DisplayClass54_0.<<CreateDatabaseIfNotExistsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync[TResult](String containerName, String databaseName, OperationType operationType, ITrace trace, Func`2 task, Nullable`1 openTelemetry, RequestOptions requestOptions, Nullable`1 resourceType)
```

Can we please get an update as to what would be the ideal way to setup an Emulator container that can be used?

If it's worth anything I tried both on a locally running app, and then a containerized version of it (localhost:8081, host.docker.internal), none of them are able to execute an operation on the emulator container even though they manage to go over the initial step of connecting **only after setting the handler to completely ignore the SSL verification**.

**Comment by xgerman** [comment]
@diegowrhasta  I believe this is a different issue. We have .NET working and I have asked @lionelc  to look into your issue - but I am wondering if you can open a separate one for the .NET issue.

**Comment by lionelc** [comment]
> Bumping this up.
> 
> Trying to follow:
> 
> https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-develop-emulator?tabs=docker-linux%2Ccsharp&pivots=api-nosql
> 
> and
> 
> https://learn.microsoft.com/en-us/azure/cosmos-db/emulator-linux#installing-certificates-for-java-sdk
> 
> With .NET Core does not work when it comes to actually connecting to the container if we want to use a certificate. The explorer is fine in my case, but when trying to connect with the `CosmosClient` class it does not accept the self-signed certificate, only doing the workaround that completely skips over the SSL validation makes it "work" but when trying to do anything, it also fails under an exception, this is what I get when simply trying to create a Database:
> 
> ```
> at Microsoft.Azure.Documents.ConsistencyReader.GetMaxReplicaSetSize(DocumentServiceRequest entity)
>    at Microsoft.Azure.Documents.ConsistencyReader.ReadAsync(DocumentServiceRequest entity, TimeoutHelper timeout, Boolean isInRetry, Boolean forceRefresh, CancellationToken cancellationToken)
>    at Microsoft.Azure.Documents.ReplicatedResourceClient.InvokeAsync(DocumentServiceRequest request, TimeoutHelper timeout, Boolean isInRetry, Boolean forceRefresh, CancellationToken cancellationToken)
>    at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass32_0.<<InvokeAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
>    at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
>    at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
>    at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
>    at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, IRetryPolicy retryPolicy)
>    at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.Handlers.RouterHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.RequestHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.Handlers.AbstractRetryHandler.ExecuteHttpRequestAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`3 callShouldRetryException, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.Handlers.AbstractRetryHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.RequestHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.Handlers.TelemetryHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.RequestHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.RequestHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.BaseSendAsync(RequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.SendAsync(String resourceUriString, ResourceType resourceType, OperationType operationType, RequestOptions requestOptions, ContainerInternal cosmosContainerCore, FeedRange feedRange, Stream streamPayload, Action`1 requestEnricher, ITrace trace, CancellationToken cancellationToken)
>    at Microsoft.Azure.Cosmos.CosmosClient.<>c__DisplayClass54_0.<<CreateDatabaseIfNotExistsAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync[TResult](String containerName, String databaseName, OperationType operationType, ITrace trace, Func`2 task, Nullable`1 openTelemetry, RequestOptions requestOptions, Nullable`1 resourceType)
> ```
> 
> Can we please get an update as to what would be the ideal way to setup an Emulator container that can be used?
> 
> If it's worth anything I tried both on a locally running app, and then a containerized version of it (localhost:8081, host.docker.internal), none of them are able to execute an operation on the emulator container even though they manage to go over the initial step of connecting **only after setting the handler to completely ignore the SSL verification**.

Hi @diegowrhasta , please make sure that you use gateway mode for the CosmosClient. The VNext emulator only supports gateway mode for now. Below is some sample code for your reference:

            HttpMessageHandler handler = new HttpClientHandler()
            {
                ServerCertificateCustomValidationCallback = (sender, certificate, chain, sslPolicyErrors) => { return true; }
            };

            CosmosClient cosmosClient = new CosmosClient(
                "http://localhost:8081",
                "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
                new CosmosClientOptions()
                {
                    ConnectionMode = ConnectionMode.Gateway,
                    HttpClientFactory = () =>
                    {
                        HttpClient client = new HttpClient(handler);
                        return client;
                    }
                });

**Comment by diegowrhasta** [comment]
Hi guys, thanks for the reply. Yup, Gateway did the trick, (so thanks!!). I do wonder if the documentation could be updated a bit just to steer people in the right direction? May it be by mentioning that the recommended approach (at least for dev purposes) would be just to skip over SSL, plus the Gateway bit. Pointing towards the samples could also be helpful imho:

https://github.com/Azure/cosmosdb-emulator-recipes/tree/main/dotnet

A bit outside of that though, I am wondering myself what the development team has in mind when it comes to the new linux emulator vs the windows one, will they still be getting updated in parallel? Will there be the introduction of http in the future, plus non-Gateway mode? I started to ask these questions after going through other issues, the docs and stuff, I do apologize if information is out there but I'm just not seeing it, but I found information in fragmented bits and I was lost at the beginning as to what emulator should I use. Thanks!

**Comment by lionelc** [comment]
@diegowrhasta Thank you for the feedback, and glad to see it works. Yes, we will keep an eye on the documentation and sample code in our next releases.

**Comment by christopheranderson** [comment]
> A bit outside of that though, I am wondering myself what the development team has in mind when it comes to the new linux emulator vs the windows one, will they still be getting updated in parallel? Will there be the introduction of http in the future, plus non-Gateway mode? I started to ask these questions after going through other issues, the docs and stuff, I do apologize if information is out there but I'm just not seeing it, but I found information in fragmented bits and I was lost at the beginning as to what emulator should I use. Thanks!

The windows (and non-preview linux) based one is the officially supported one and will continue to get new capabilities. Those are still the recommended emulators for most customers. Those emulators, however, do not work on Apple Silicon based hardware. 

The new "preview linux" emulator uses a different approach to emulation which has enabled us to support Apple Silicon, but it lacks full compat at the moment, in particular with query. We've also managed to slim down the emulator container substantially, which has improved the experience in CI systems. However, we still don't have a date we can share on when it would be generally available and supported in all scenarios. Many of the missing features take some substantial work, so when issues are filed, we might not always be able to turn it around quickly. We'd only recommend you use the preview emulator if you're on Apple Silicon, and if you're blocked, you'd need to fall back to using the live service.

If you can use the existing generally available emulators, that would be the recommendation today. When we make the new preview linux emulator generally available, we'd still support the existing emulators for some time until we were confident the new emulator had addressed all the necessary scenarios.

**Comment by lionelc** [comment]
@awebre @hectortosa for the access issue with data explorer, we released a version on Jan 22 to fix "--protocol https". I just tested it again on my end with the same command `docker run -p 8081:8081 -p 1234:1234 mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview --protocol https --enable-explorer true --explorer-protocol 1234 --log-level trace` . Then `http://localhost:1234` is good for me. You may try again with the updated image.

**Comment by lionelc** [comment]
> [@awebre](https://github.com/awebre) [@hectortosa](https://github.com/hectortosa) for the access issue with data explorer, we released a version on Jan 22 to fix "--protocol https". I just tested it again on my end with the same command `docker run -p 8081:8081 -p 1234:1234 mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview --protocol https --enable-explorer true --explorer-protocol 1234 --log-level trace` . Then `http://localhost:1234` is good for me. You may try again with the updated image.

Also note that the option `--protocol https` is for the gateway endpoint (we support gateway mode only), and the data explorer is on http this way.

**Comment by lionelc** [comment]
> Hi guys, thanks for the reply. Yup, Gateway did the trick, (so thanks!!). I do wonder if the documentation could be updated a bit just to steer people in the right direction? May it be by mentioning that the recommended approach (at least for dev purposes) would be just to skip over SSL, plus the Gateway bit. Pointing towards the samples could also be helpful imho:
> 
> https://github.com/Azure/cosmosdb-emulator-recipes/tree/main/dotnet
> 
> A bit outside of that though, I am wondering myself what the development team has in mind when it comes to the new linux emulator vs the windows one, will they still be getting updated in parallel? Will there be the introduction of http in the future, plus non-Gateway mode? I started to ask these questions after going through other issues, the docs and stuff, I do apologize if information is out there but I'm just not seeing it, but I found information in fragmented bits and I was lost at the beginning as to what emulator should I use. Thanks!

Per your request, this is some sample code in C#, while we are in the process of merging them into the main emulator recipes repo: 
https://github.com/lionelc/cosmosdb-emulator-recipes/tree/main/vnext/code-samples/dotnet .
