### ISSUE TITLE
Application can't connect to cosmos emulator container

### ISSUE THREAD

**Issue by pmkama** [Azure/azure-cosmos-db-emulator-docker#136]
**Describe the bug**

Hi team ! I am new to cosmos and the emulator ! Trying to set up my local dev env using the vnext preview emulator but having trouble to start the emulator and connect my app with it. The emulator container started successfully. But when I start my application, It fails with the error below. 
`Caused by: com.azure.cosmos.CosmosException: {"innerErrorMessage":"System.NotImplementedException: Have not implemented Read on Address.\n   at Microsoft.Azure.Cosmos.Postgres.Core.Interop.SqlOperationHandler.ProcessSqlRequestAsync(SqlRequest request, PostgresClient client, CancellationToken cancellation) in /tmp/gateway/Cosmos.Postgres.Core/Interop/SqlOperationHandler.cs:line 288\n`. 

From the container, I see the following log:
`DocDBTrace Information: 0 : Npgsql Non-Transaction settings -c idle_in_transaction_session_timeout=60000 -c statement_timeout=60000 
2024-12-03 09:59:36 DocDBTrace Error: 0 : Failed request processing System.NotImplementedException: Have not implemented Read on Address.
2024-12-03 09:59:36    at Microsoft.Azure.Cosmos.Postgres.Core.Interop.SqlOperationHandler.ProcessSqlRequestAsync(SqlRequest request, PostgresClient client, CancellationToken cancellation) in /tmp/gateway/Cosmos.Postgres.Core/Interop/SqlOperationHandler.cs:line 288
2024-12-03 09:59:36    at Microsoft.Azure.Cosmos.Postgres.Core.Interop.SqlOperationHandler.ProcessRequestAsync(SqlRequest request, PostgresClient client) in /tmp/gateway/Cosmos.Postgres.Core/Interop/SqlOperationHandler.cs:line 61
2024-12-03 09:59:36    at Microsoft.Azure.Cosmos.Postgres.Core.Interop.SqlRequestPipeline.ProcessRequestAsync(KestrelHttpRequestContext transportRequest) in /tmp/gateway/Cosmos.Postgres.Core/Interop/SqlRequestPipeline.cs:line 56`

I am using the cosmos java SDK on Mac OS on M3. 

I am not sure this is a bug, but would appreciate any help with that. 

**Additional context**
{"userAgent":"azsdk-java-cosmos/4.63.2 MacOSX/15.1.1 JRE/21.0.5"

**Comment by pmkama** [comment]
Changing the mode to gateway help me start the application !
