### ISSUE TITLE
Ability to set consistency level

### ISSUE THREAD

**Issue by timabell** [Azure/azure-cosmos-db-emulator-docker#141]
**Is your feature request related to a problem? Please describe.**

Calls to the emulator that request strong consistency fail.

The request is using the options when creating an item:

```csharp
await container.CreateItemAsync
(
    item: item,
    partitionKeyValue,
    new ItemRequestOptions { ConsistencyLevel = ConsistencyLevel.Strong },
    cancellationToken
);

```

I got an exception because the code was requesting "strong" consistency, which for our real azure environment is fine, but the emulator rejected it with the following

```
System.ArgumentException
ConsistencyLevel Strong specified in the request is invalid when service is 
configured with consistency level Session.
Ensure the request consistency level is not stronger than the service
consistency level.

   at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.ValidateAndSetConsistencyLevelAsync(RequestMessage requestMessage)
   at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler.SendAsync(String resourceUriString, ResourceType resourceType, OperationType operationType, RequestOptions requestOptions, ContainerInternal cosmosContainerCore, FeedRange feedRange, Stream streamPayload, Action`1 requestEnricher, ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ContainerCore.ProcessItemStreamAsync(Nullable`1 partitionKey, String itemId, Stream streamPayload, OperationType operationType, ItemRequestOptions requestOptions, ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ContainerCore.ExtractPartitionKeyAndProcessItemStreamAsync[T](Nullable`1 partitionKey, String itemId, T item, OperationType operationType, ItemRequestOptions requestOptions, ITrace trace, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ContainerCore.CreateItemAsync[T](T item, ITrace trace, Nullable`1 partitionKey, ItemRequestOptions requestOptions, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync[TResult](String containerName, String databaseName, OperationType operationType, ITrace trace, Func`2 task, Func`2 openTelemetry, String operationName, RequestOptions requestOptions)
   at Microsoft.Azure.Cosmos.ClientContextCore.<>c__DisplayClass31_0`1.<<OperationHelperWithRootTraceWithSynchronizationContextAsync>b__0>d.MoveNext()
...
```

**Describe the solution you'd like**

The ability to set an environment variable on the comsodb docker container to be make it fake the other consistency levels. It is understood that it doesn't really implement them (which makes sense because it's a single running container instance not a multi-region deployment), but as close as we can get to realistic behaviour / API behaviour the better.

**Describe alternatives you've considered**

- Giving up on the emulator and running the tests against CosmosDB in Azure
- Trying the non-docker CosmosDB on linux
- Trying the non-docker CosmosDB on windows

I'd rather not do any of these, I'm trying to get a repeatable and isolated test environment, ideally with devcontainers.

**Additional context**

The ComsosDB Emulator is being used as part of dotnet core test run, and is accessed by both the dotnet service under test (which would use the real Azure Cosmos when in production), and by the test code to do setup/teardown of state within the CosmoDB emulator.

I'm using the [Docker containerized CosmosDB Emulator](https://github.com/Azure/azure-cosmos-db-emulator-docker) with a dotnet core test project.

I've read up on the consistency models, so I get why you can't ask for strong when the cosmos is configured for the weaker "session" consistency. But I can't find any reference for how to make the emulator act like it's in "strong" mode. I don't want to change the code as it's been written to use "strong" presumably for good reason, and weakening the request could break something subtle but important in the system I'm looking at.

- https://learn.microsoft.com/en-us/azure/cosmos-db/consistency-levels
- https://learn.microsoft.com/en-us/azure/cosmos-db/emulator
- https://learn.microsoft.com/en-us/azure/cosmos-db/emulator-linux (the one that runs in docker)

It seems the windows cosmosdb emulator has a [command line argument to set consistency](https://learn.microsoft.com/en-us/azure/cosmos-db/emulator-windows-arguments), but I don't see an equivalent in the documentation for the linux/docker versions.

```ps
Microsoft.Azure.Cosmos.Emulator.exe /Consistency=Strong
```
 
Same question here https://stackoverflow.com/questions/79257695/how-do-you-set-the-account-consistency-level-the-cosmosdb-emulator-in-docker

**Comment by timabell** [comment]
Well, I found a way to do it, but it's not documented.

Add it via additional args:

```yml
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    environment:
      AZURE_COSMOS_EMULATOR_ARGS: "/Consistency=Strong"
```

This is passed through by the `start.sh` file in the emulator:

```
docker exec -it devcontainer-cosmosdb-1 /bin/bash

root@a3ea5276c3a3:/usr/local/bin/cosmos/bin#
grep --line-number OTHER_ARGS start.sh 

11:EMULATOR_OTHER_ARGS="${AZURE_COSMOS_EMULATOR_ARGS:-/enablepreview}"
14:     EMULATOR_OTHER_ARGS="$EMULATOR_OTHER_ARGS /EnableMongoDBEndpoint=${AZURE_COSMOS_EMULATOR_ENABLE_MONGODB_ENDPOINT}"
16:     EMULATOR_OTHER_ARGS="$EMULATOR_OTHER_ARGS /nocompute"
70:./cosmosdb-emulator -w $COSMOS_APP_HOME/appdata -- /Microsoft.Azure.Cosmos.Emulator.exe /enablepreview /disableRIO /minimal $EMULATOR_PARTITION_SETTINGS /disablethrottling $EMULATOR_CERTIFICATE_OPTION /alternativenames=$EMULATOR_IP_ADDRESS,$EMULATOR_OTHER_IP_ADDRESSES /alternativeips=$EMULATOR_IP_ADDRESS,$EMULATOR_OTHER_IP_ADDRESSES /publicipaddressoverride=$EMULATOR_IP_ADDRESS /AllowNetworkAccess /Key=$EMULATOR_KEY $EMULATOR_OTHER_ARGS
```

I think it would be good to add this to the docs, or better still add a specific argument to the docker container as has been done for other settings.
